datasources:
- name: 'InfluxDB'
  type: 'influxdb'
  access: 'proxy'
  org_id: 1
  url: 'http://influxdb:8086'
  is_default: false
  version: 1
  editable: true
  user: admin
  password: admin
  database: luftdaten
